######################################################################
# Automatically generated by qmake (3.0) Mi. Mrz 31 13:35:23 2019
######################################################################

QT += testlib sql
TEMPLATE = app
TARGET = qtconnectionpool_tests
CONFIG += console

# Input
HEADERS += \
    database/databaseconnectiontest.h \
    database/poolconfigtest.h \
    database/connectionpooltest.h \
    database/testHelpers/asyncconnectionuser.h \
    database/testHelpers/PrgLog.h \
    database/testHelpers/helperfunctions.h
SOURCES += main.cpp \
    database/databaseconnectiontest.cpp \
    database/poolconfigtest.cpp \
    database/connectionpooltest.cpp \
    database/testHelpers/asyncconnectionuser.cpp \
    database/testHelpers/PrgLog.cpp \
    database/testHelpers/helperfunctions.cpp

#include(../QtConnectionPool/qtconnectionpool.pro)

LIBS += -lqtconnectionpool -L../bin
INCLUDEPATH += $$PWD/../QtConnectionPool

DESTDIR = ../bin

CONFIG += test_config
test_config.files = $$files(etc/*.json)
test_config.path = $$DESTDIR/etc

RESOURCES += \
    test_resources.qrc


